# Generated by Django 5.0 on 2024-01-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='image',
            field=models.ImageField(upload_to='clients'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(upload_to='services'),
        ),
    ]
