# Generated by Django 5.0 on 2024-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clients_image_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
